spring:
  application:
    pipeline:
      source:
        fields: >
          title,
          description,
          state,
          trigger

    schedule:
      group: group_1
  data:
    elasticsearch:
      protocol: http
      cluster-name: elasticseash
      cluster-nodes: "localhost:9200"
  quartz:
    auto-startup: true
    job-store-type: memory
    scheduler-name: pipeline-trigger
    startup-delay: 5s
    #    http://www.quartz-scheduler.org/documentation/quartz-2.1.7/configuration/
    properties:
      org.quartz.threadPool.threadCount: 5



